### ISSUE TITLE
highlight unused imports when the usage is commented out

### ISSUE THREAD

**Issue by Acr0most** [marabesi/php-import-checker#10]
because you only check regex from whole document content, your extension does not highlight when the usage is commented out.

![bildschirmfoto 2018-11-12 um 10 33 30](https://user-images.githubusercontent.com/36692230/48338671-865b8e80-e666-11e8-84c6-12348c92fd8d.png)

**Comment by marabesi** [comment]
That's true, I had to comment a few tests cases in the test folder.

The thing is that I couldn't thing a way of implement it without a parse, to read and analyse the code. The php-parse package does a great job at it, so the ext would have to parse the ast and do the trick.

**Comment by marabesi** [comment]
Pseudo code so far:

```javascript 
const ast = require('./ast.json'); 
const useStatements = [];

function vist(node) {
    if (typeof node.forEach !== 'function') return;

    node.forEach(element => {
        if (element.kind === "usegroup") {
            for (let useItem in element.items) {
                useStatements.push(useItem);
            }
        }

        if (element.children) {
            vist(element.children);
        }

        if (element.body) {
            vist(element.body);
        }
    });
}

vist(ast.children);
```

**Comment by marabesi** [comment]
Potentially fixed in the version 0.6.0:

![image](https://user-images.githubusercontent.com/2129872/144721039-39eefdde-7495-4266-b945-f94aa080f685.png)

**Comment by marabesi** [comment]
reopen as the versions released under 0.6.* are all buggy and not working.

Anyways, I think this will require some configuration to turn on/off comments. I have been thinking on this issue and it seems correct to take into account commented classes. For example, when you use `@var` to explicitly declare the variable type (symfony has this pattern for example).

refs #303

**Comment by marabesi** [comment]
I released a few improvements on namespaces, would be god to have some feedback on this one. To test it you should have the following settings:

```json
"php.import.highlight": {
   "use_next_version": true
  "ignore_comments": true
}
```

**Comment by marabesi** [comment]
closing for lack of feedback
