### ISSUE TITLE
Importing global functions without backslash causes them to show as unused.

### ISSUE THREAD

**Issue by neufena** [marabesi/php-import-checker#15]
an example of this:

use function assert;

gets highlighted in red as unused but

use function \assert;

does not.

**Comment by marabesi** [comment]
Could you give an example with real code?

Something like the examples in the repo https://github.com/marabesi/php-import-checker/blob/master/test/examples/snippet9.php

**Comment by neufena** [comment]
Sorry for the delay.  This code highlights line 11 red:

<?php

/**
 * Should not highlight used function
 */

namespace App;

use Example;

use function assert;

class Test
{
    public function foo() : Example
    {
        assert(true);
         // ...
    }
}
